### ISSUE TITLE
Update Service Image versioning on Release

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1136]
As external users currently have difficulty knowing which versions of the Service Images are "stable," it is desired to update the container image versioning to correlate to the release versioning when we provide releases. These images will be considered the "official" images, and will be used for logging issues. Other images, built on each commit to `master`, will be considered development.

---

**Tasks:**
- [x] Build a Github Action or CircleCI pipeline which triggers on the publish of a Release
- [x] Use the commit tag from that release to find the images which were built on that commit
- [x] Add an additional tag to these images with the Release Version included
_If the commit ID cannot be parsed from the images,_
- [x] Re-build the images from the released commit, and publish them again to Docker Hub

---
