### ISSUE TITLE
Create SDF architecture concept

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#115]
As a product manager I want a description of the SDF architecture, so that 3rd parties are able to understand the underlying concept.

Further description:

Several architecture decisions werde made in #74 . We need to create an SDF architecture concept that is derived from these decisions:

- [Integration Layer](https://github.com/openintegrationhub/Architecture/blob/ad9842399f98fa44f85606839bedf9dc074e5b8a/Decisions/closed/integrationLayer.md)
- [Integration Patterns](https://github.com/openintegrationhub/Architecture/blob/ad9842399f98fa44f85606839bedf9dc074e5b8a/Decisions/closed/integrationPatterns.md)
- [Interaction Styles](https://github.com/openintegrationhub/Architecture/blob/ad9842399f98fa44f85606839bedf9dc074e5b8a/Decisions/closed/interactionStyles.md)
- [Object Completeness](https://github.com/openintegrationhub/Architecture/blob/ad9842399f98fa44f85606839bedf9dc074e5b8a/Decisions/closed/objectCompleteness.md)
- [Transformer Location](https://github.com/openintegrationhub/Architecture/blob/ad9842399f98fa44f85606839bedf9dc074e5b8a/Decisions/closed/transformerLocation.md)
- [Request Missing Information](https://github.com/openintegrationhub/Architecture/blob/6c21871048866b32f9359606aaa2b325b4c77c9b/Decisions/closed/requestMissingInformation.md)

**TODO's:**

- [ ] Consolidate SDF information from previous concepts and decisions made in #74 
- [ ] Create graphics which use proper wording to enhance comprehensibility 
---

**Acceptance Criteria:**
- [ ] Architecture description is created 
- [ ] SDF architecture concept has been reviewed and accepted by the workgroup

**Comment by fdegenhr** [comment]
Currently the connectors are described (https://github.com/openintegrationhub/Connectors) to support the complete functionality of the adapter (https://github.com/openintegrationhub/Connectors/blob/master/Adapters/AdapterBehaviorStandardization/StandardizedActionsAndTriggers.md).
Is this still valid?

**Comment by philecs** [comment]
On basis of new decisions this task is on hold. E.io will publish currently existing services under the hood of the Open Integration Hub. See #119 and #118 .
