### ISSUE TITLE
Reconsideration: services API docs

### ISSUE THREAD

**Issue by heggert** [openintegrationhub/openintegrationhub#1194]
Current situation:

All our services API docs are located in service folders and written in Swagger/OpenAPI conform format. Based on this a human-readable format is available through a specific API Endpoint on every service. However, every service needs to be started first to read his API spec.

Open for discussion:

**Should we centralize the source for every API spec?**

**Should we prerender and store all API specs to make them accessible although services have not been started before?**

**Comment by weberjm** [comment]
After discussion, we will provide a central location to view the API documentation. This will allow external developers to review the framework API without requiring the specific services to be deployed on our test servers. 

A couple of sources for investigation of best solutions:
- [OpenAPI Tools List](https://openapi.tools/#documentation) - Variety of tools to help with creating docs from API specs
- [jekyll-openapi](https://github.com/robertlove/jekyll-openapi) - We could deploy the API information with our documentation site

### Tasks
- [ ] Build API documentation on update of specs
- [ ] Deploy documentation where it is always available
- [ ] Update links from current documentation to point to new API pages

**Comment by heggert** [comment]
Taking @weberjm remarks into account I did some research on how we could integrate our API documentation into our existing docs. As it turned out, there are various possibilities and it is essential that a discussion and decision take place before implementation. So in the following, I would like to introduce three possible approaches more specifically: 

**1. Standalone API Docs as GitHub pages**
see https://github.com/robertlove/jekyll-openapi

- API specs are stored in a different repository
- easy to use, e.g. just copy "openapi.json" to service/ folder and push

**2. Standalone API Docs as own service**
see https://github.com/Mermade/widdershins

- deployment needed
- complex setup
- most flexible
- API specs could be fetched dynamically from a different repository

**3. Build with "openapi-generator-cli" copy to docs-repo**
- requires JAVA
- implies inter repository workflow
- needs a script to setup everything properly
- could be done manually or automated within our build pipeline
- generates simple HTML which can be easily integrated into a Jekyll page
