### ISSUE TITLE
Integration Tests for Services

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#121]
As quality manager, I want to use integration tests for all services

Further description:
Based on the service architecture roadmap, we need use cases for possible data flows between single services, e.g. 'login'
---

**Acceptance Criteria:**
- [x] accepted/agreed on testing framework(s)
- [ ] initial setup for one n-m test (techn.: frameworks e.g.)
- [ ] create/write use cases for data flows
- [ ] automated running (of all avail.) current integration tests
