### ISSUE TITLE
Define/Describe integration tests

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#142]
As a quality manager, I want to perform integration tests to make sure our services are able to communicate correctly with each other

**Further description:**
Currently we do not have any integration tests for our central testing instance. We need to define use cases and test cases for currently available services and future services. Test cases can act as a guide for future development of framework services.

- [x] Decide on testing framework
- [x] Collect use cases for current services
- [x] Collect use cases for upcoming services
- [x] Derive integration tests from use cases 

---

**Acceptance Criteria:**

- [x] Tests are implemented
- [x] Pipeline is adjusted to cover integration tests

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by DennisCES** [comment]
1. Setting up services locally wasnt possible, ICR failed 
2-4 will be discussed in fridays meeting considering the test/build/deploy process and further approaches
