### ISSUE TITLE
Implement data hub

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#182]
As product manager, I expect a requirement document, technical concept and implemented code including test cases, to provide smart data feature to other backend services.

**Further description:**

- [x] Collect requirements for master data service
   - [x] Data Security (e.g. DSGVO)
   - [x] Data Structure (Unstructured data lake? relational database? ...)
   - [x] Client/Tenant Management (access control) 
- [x] Define basic scope of master data service
- [x] Evaluate existing open source technologies

---

**Acceptance Criteria:**
- [x] Requirements documented
- [x] Basic scope documented
- [x] Prototype implemented and released

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
