### ISSUE TITLE
Implement Component Orchestrator Alpha

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#184]
As product manger I want efficient resource handling to be in place.

---

**Acceptance Criteria:**
- [x] Independent to specific container framework 
- [x] Concept orchestration for container and services 
- [x] Technical documentation for prototype (to operate the open integration hub)

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by drobiazko** [comment]
@philecs @pnedelko this one can be closed, I guess. We need to create a bunch of specific issues to make resource coordinator become beta.
