### ISSUE TITLE
Implement Component Orchestrator Beta

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#185]
As product manger I want efficient resource handling to be in place.

---

**Acceptance Criteria:**
- [ ] Independent to specific container framework 
- [ ] Concept orchestration for container and services 
- [ ] Technical documentation for prototype (to operate the open integration hub)
- [ ] Review alpha version and define scope mismatch and possible new features

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
