### ISSUE TITLE
Implement Component Repository Alpha

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#187]
As a product manager, I want a central repository for storing integration components and handle versions and updates.

**Further description:**

- [x] Concept for versioning
- [x] Concept for component co-existence
- [x] Concept for component update/upgrade mechanisms
- [x] Implement prototype
- [x] Prototype documentation

---

**Acceptance Criteria:**
- [x] Concept agreed by work group and released on github
- [x] Prototype implemented and documented

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
