### ISSUE TITLE
SetUp Build/Deploy Pipeline with CircleCi

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#188]
As quality manager I build and deployment pipline that is set up for the monorepo and documented so that services are properly built and deployed.

**Further description:** 

- [x] Setup CircleCI
- [x] Define config.yml so that it reflects our project configuration.
- [x] Update all partners about the pipeline and provide support for next steps

--- 

**Acceptance Criteria:** 

- [x] CircleCi setup and config.yml defined
- [x] Common understanding about pipeline

---

 [**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by DennisCES** [comment]
update: @pnedelko will add his config.yaml initially, others can adapt and extend the code with their service-specific build/test stages/jobs
