### ISSUE TITLE
Update project plan for AP (working package) 4

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#20]
As product owner I want to have an updated development plan to create a common understanding of the time critical services. 

In order to create a new overall development plan a new project plan for AP 4 is needed by each partner.

---

**Acceptance Criteria:**
- [x] Update the old project plan including resource and time planning
- [x] Add actual available resources (current excel sheet includes resource planning before cutback)
- [x] Send the updated project plan to Philipp
