### ISSUE TITLE
Make services independent of K8s CRD

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#203]
As product manager I want services to be independent of K8s CRD, so that there is no tight coupling between oih and a specific orchestration tool.

**Further description:**

- [x] Make scheduler independent of K8s CRD
- [x] Make communication router/scheduler independent of K8s CRD

---

**Acceptance Criteria:**
- [x] All services are independent of K8s CRD

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
