### ISSUE TITLE
Review and extend the metadata repository spec

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#220]
As an OiH developer, I want to have a clear understanding what this service does so that I can implement it.

- [x] Review current documentation
- [x] Extend if required after agreeing on it with elastic and wice
- [x] Create API Specs

---

**Acceptance Criteria:**
- [x] Meta Data Service specs created incl. api specs

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Updated basic description: https://github.com/openintegrationhub/Microservices/blob/master/RepositoryManagement/MetaDataService.md

**Comment by philecs** [comment]
Open points:

- We need to decide on how the validator decides against which domain object of a given (master data) model the incoming object should be validated. Currently we can only reference whole models but not specific domain objects (e.g. person object from address model).
- API specification needed

**Comment by sachmerz** [comment]
@philecs that's one of the questions I have as well. The following definition in https://github.com/openintegrationhub/Data-and-Domain-Models/tree/master/MasterDataModels#json-schema says:

> in a way an OIH instance is able to validate data at runtime. And, as OMDMs are split into sub-models and the records of those sub-models must be processable independently,

> * for every sub-model of an OMDM there must be a seperate JSON schema describing the entity or aggregate.

If a sub-model is stored in a separate JSON schema, then I guess such sub-models could be accessed by a unique URI?

**Comment by philecs** [comment]
@sachmerz at least that is the way I would handle it with the current knowledge.
Examples for sub-models of the address model [address sub-models](https://github.com/openintegrationhub/Data-and-Domain-Models/tree/master/src/main/schema/addresses).

**Comment by sachmerz** [comment]
@drobiazko provided a version of the API spec https://app.swaggerhub.com/apis/elasticio/metadata-service/0.0.2#/, which we slightly adjusted, as it already resembles the minimal requirements for the first version: https://app.swaggerhub.com/apis/basaas5/metadata-service/0.0.2
