### ISSUE TITLE
Create Specification for  data hub

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#223]
As a product manager I want proper specifications so that we have a common understanding for the subsequent implementation.

**Further description:**

- [x] Gather requirements
- [x] Consolidate requirements
- [x] Create Swagger Specs
- [ ] Align with partners
- [ ] Create functionality description

---

**Acceptance Criteria:**
- [ ] Meta data specs created

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
