### ISSUE TITLE
Create audit log specs

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#232]
As a product manager I want proper specifications so that we have a common understanding for the subsequent implementation.

**Further description:**

- [x] Gather requirements
- [x] Consolidate requirements
- [x] Create Swagger Specs
- [x] Create further specifications such as message format

---

**Acceptance Criteria:**
- [ ] Audit Log specs created, reviewed and accepted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
