### ISSUE TITLE
Create meta data specs

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#235]
As a product manager I want proper specifications so that we have a common understanding for the subsequent implementation.

**Further description:**

- [x] Gather requirements
- [x] Consolidate requirements
- [x] Create Swagger Specs
- [x] Create functionality description

---

**Acceptance Criteria:**
- [x] Meta data specs created

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
