### ISSUE TITLE
Improve framework documentation

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#421]
As a user I want to know how to properly use the framework, so that I am able to create integrations.

**Further description:**

- [x] Enhance service api documentations
- [x] Provide postman configuration
- [x] Provide technical documentation on how to use the platform

**Comment by philecs** [comment]
New Documentation EPIC
