### ISSUE TITLE
Update metadata docs

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#512]
The current docs are outdated.

**Further description:**

- [x] Document how to upload schemas in api docs (Currently it is not clear how multiple schemas can be uploaded)
- [x] Fix url (should be `/domains/{domainId}/schemas/import`)
- [x] Metadata docs have no `authorization` button
- [x] Fix url's. Change from e.g. `/domains` to `api/v1/...`
- [x] Add missing http error / statuscodes

---

**Acceptance Criteria:**
- [x] Metadata repository docs updated

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
As discussed issue will be closed. Status codes tbd in sprint review
