### ISSUE TITLE
Implement Hub & Spoke Model

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#655]
Hub & Spoke model has to be implemented.

**Further description:**

- [ ] Specify handling of envVars in flow nodes
- [ ] Specify validation use case / interactions
- [ ] Implement dispatcher service
- [ ] Implement handling of recordUid of external systems

---

**Acceptance Criteria:**
- [x] All todo's solved

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
