### ISSUE TITLE
Existing NodeJS connectors have to provide meta information

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#670]
Meta information must be provided by an adapter in order to properly use the hub and spoke model.
These meta information include:

- [ ] applicationUid 

Meta information must be provided by a transformer in order to properly use the hub and spoke model.
These meta information include:

- [ ] meta information provided by the adapter
- [ ] recordUid ( =uid within the source system)
- [ ] domainID of the domain of the relating oih data model
- [ ] Schema URI of the relating oih data model

---

**Acceptance Criteria:**
- [ ] Existing Adapters adjusted
- [ ] Existing Transformers adjusted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
- [x] dreamrobot adapter
- [x] dreamrobot transformer
- [x] github adapter
- [x] XWorks365 adapter
- [x] XWorks365 transformer
- [x] SnazzyContacts adapter
- [x] SnazzyContacts transformer
- [x] WiceCRM adapter
- [x] WiceCRM transformer
- [x] getMyInvoice adapter
- [x] getMyInvoice transformer
- [x] msoffice adapter
- [x] msoffice transformer

**Comment by philecs** [comment]
- https://github.com/openintegrationhub/xworks365-adapter
- https://github.com/openintegrationhub/xworks365-transformer
- https://github.com/openintegrationhub/getmyinvoice-adapter
- https://github.com/openintegrationhub/getmyinvoice-transformer
- https://github.com/openintegrationhub/dreamrobot-adapter
- https://github.com/openintegrationhub/dreamrobot-transformer
- https://github.com/openintegrationhub/ms-office-transformer
- https://github.com/openintegrationhub/github-adapter
- https://github.com/openintegrationhub/snazzycontacts-adapter
- https://github.com/openintegrationhub/snazzycontacts-transformer
- https://github.com/openintegrationhub/wicecrm-adapter
- https://github.com/openintegrationhub/wicecrm-transformer
