### ISSUE TITLE
Create detailled Identitiy Management (Microservice) Description

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#7]
The microservice description aims to create a common understanding throughout all OIH-members. It should answer relevant organizational and substantial questions.

## Sub-Tasks
- [ ] **Assignees** defined
- [ ] **Estimate** guessed
- [ ] Create a template for the microservice description 
- [ ] Store the template on a central repository so every participant, involved in the OIH project can access it
- [ ] Make initial propositions for the subitems of the microservice description
- [ ] Reconciliation with the AP / microservice lead
- [ ] Forward the revised version to all parties involved in the microservice
- [ ] Discuss critical points and find consensus
- [ ] Communicate the final version of the microservice description

### Votes against alternative
`#`issue `@`member

### Definition of Done
- [ ] No open sub-tasks
