### ISSUE TITLE
Build/Deployment Process for OIH

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#72]
A decision on how the deployment process should look like is needed. 

- [x] Decide what CI tool to use (Suggestions: TravisCI, CircleCI, Jenkins)
- [x] Decide how to build services independently
- [x] Decide how to deploy different branches independently

Further description:
Currently there is no common way to deploy new services. To create a team overwhelming process how new services some investigation is necessary.

---

**Acceptance Criteria:**
- [x] Documented deployment process (todo results)
- [x] Agreed on deployment process
- [x] Guideline is Reviewed and merged #29

**Comment by falkvoigt** [comment]
We Decide for TravisCI for the Start.
