### ISSUE TITLE
Existing Java Connectors have to provide meta information

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#764]
Meta information must be provided by an adapter in order to properly use the hub and spoke model.
These meta information include:

- [ ] applicationUid 

Meta information must be provided by a transformer in order to properly use the hub and spoke model.
These meta information include:

- [ ] meta information provided by the adapter
- [ ] recordUid ( =uid within the source system)
- [ ] domainID of the domain of the relating oih data model
- [ ] Schema URI of the relating oih data model

---

**Acceptance Criteria:**
- [ ] Existing Adapters adjusted
- [ ] Existing Transformers adjusted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
