### ISSUE TITLE
Establish Notification and Event Bus

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#98]
Further description:

Clarification is needed if this service is still needed or not. If the service is needed it must be properly described and implemented.

- [x] Clarify need for and scope for a notification and event bus
- [x] Create a concept for the notification and event bus or write a short text why the service is no longer needed 
- [x] If the service is needed: It must be implemented 

---

**Acceptance Criteria:**
- [x] Decision on need for the service was made
- [x] Concept or statement was created
- [x] Service is implemented

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)
